[package]
name = "smartpack_rust_crates"
version = "0.1.0"
edition = "2021"
authors = ["Taha Moeini"]
homepage = "https://taha.one"
repository = "https://github.com/tahamoeini/smartpack"

[dependencies]
flate2 = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
tar = "0.4"
